name: Trading Alert
on:
  workflow_dispatch: {}
  schedule:
    - cron: "5 21 * * 1-5"
jobs:
  check-signal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: python main.py alert --ticker EURUSD=X --ntfy-topic rilleyfx200913
